export const SAVE_REPLAY_TEXT = 'SAVE_REPLAY_TEXT'
export const SEARCH_REPLAY_DATAS = 'SEARCH_REPLAY_DATAS'
export const RUN_ACTIONS = 'RUN_ACTIONS'
export const BG_RUN_ACTION = 'BG_RUN_ACTION'
export const SAVE_TEMPORARY_DATA = 'SAVE_TEMPORARY_DATA'
export const GET_TEMPORARY_DATA = 'GET_TEMPORARY_DATA'
export const OPEN_NEW_TAB = 'OPEN_NEW_TAB'

export const DETACH_DEBUGGER = 'DETACH_DEBUGGER'
export const DEBUGGER_CLICK = 'DEBUGGER_CLICK'

export const ATTACH_DEBUGGER = 'ATTACH_DEBUGGER'

export const DEBUGGER_CLICK_XY = 'DEBUGGER_CLICK_XY'